version: '3.1'
services:
  app:
    container_name: app-nzapi
    image: app-nzapi
    build: ./
    ports:
      - "8080:8080"
    environment:
      CLIENT_SECRET: ${CLIENT_SECRET}
      CLIENT_ID: ${CLIENT_ID}
      JDBC_DATABASE_PASSWORD: ${JDBC_DATABASE_PASSWORD}
      JDBC_DATABASE_USERNAME: ${JDBC_DATABASE_USERNAME}
      JWT_SECRET: ${JWT_SECRET}
      MELHOR_IO_URL: ${MELHOR_IO_URL}
      REDIRECT_URI: ${REDIRECT_URI}
      USER_AGENT: ${USER_AGENT}
      JDBC_DATABASE_URL: ${JDBC_DATABASE_URL}
      MELHOR_ENVIO_URL: ${MELHOR_ENVIO_URL}
      RECOVERY_URL: ${RECOVERY_URL}
      EMAIL_FROM: ${EMAIL_FROM}
      FIRST_ACCESS_URL: ${FIRST_ACCESS_URL}
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${JDBC_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${JDBC_DATABASE_PASSWORD}
