version: '3.1'
services:
  app:
    container_name: app-nzapi
    image: app-nzapi
    build: ./
    network_mode: host
    environment:
      CLIENT_SECRET: ${CLIENT_SECRET}
      CLIENT_ID: ${CLIENT_ID}
      JDBC_DATABASE_PASSWORD: ${JDBC_DATABASE_PASSWORD}
      JDBC_DATABASE_USERNAME: ${JDBC_DATABASE_USERNAME}
      JWT_SECRET: ${JWT_SECRET}
      MELHOR_IO_URL: ${MELHOR_IO_URL}
      REDIRECT_URI: ${REDIRECT_URI}
      USER_AGENT: ${USER_AGENT}
      JDBC_DATABASE_URL: ${JDBC_DATABASE_URL}
      MELHOR_ENVIO_URL: ${MELHOR_ENVIO_URL}
      RECOVERY_URL: ${RECOVERY_URL}
      EMAIL_FROM: ${EMAIL_FROM}
      FIRST_ACCESS_URL: ${FIRST_ACCESS_URL}
      KEY_STORE_PASSWORD: ${KEY_STORE_PASSWORD}
      KEY_STORE: keystore.p12
      REDIS_COMMAND: ${REDIS_COMMAND}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      WEBHOOK_URL: ${WEBHOOK_URL}
      MERCADO_PAGO_URL: ${MERCADO_PAGO_URL}
      MERCADO_PAGO_TOKEN: ${MERCADO_PAGO_TOKEN}
      NZ_SMTP_HOST: ${NZ_SMTP_HOST}
      NZ_SMTP_PORT: ${NZ_SMTP_PORT}
      NZ_PASSWORD: ${NZ_PASSWORD}
      NZ_EMAIL: ${NZ_EMAIL}
    depends_on:
      - dbpostgresql
      - redis
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${JDBC_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${JDBC_DATABASE_PASSWORD}
  redis:
    image: redis
    command: ${REDIS_COMMAND}
    ports:
      - "6379:6379"