FROM openjdk:11
VOLUME /tmp
EXPOSE 8080
ENV CLIENT_SECRET $CLIENT_SECRET
ENV CLIENT_ID $CLIENT_ID
ENV JDBC_DATABASE_PASSWORD $JDBC_DATABASE_PASSWORD
ENV JDBC_DATABASE_USERNAME $JDBC_DATABASE_USERNAME
ENV JWT_SECRET $JWT_SECRET
ENV MELHOR_ENVIO_URL $MELHOR_ENVIO_URL
ENV REDIRECT_URI $REDIRECT_URI
ENV USER_AGENT $USER_AGENT
ENV JDBC_DATABASE_URL $JDBC_DATABASE_URL
COPY build/libs/nzapi-0.0.1-SNAPSHOT.jar nzapi.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-Dspring.profiles.active=dev","-jar","/nzapi.jar"]
