server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
spring:
  redis:
    host: localhost
    port: 6379
    password:
  cache:
    type: redis
  datasource:
    hikari:
      maximumPoolSize: 20
      max-active: 20
      max-idle: 10
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345
  jpa:
    databasePlatform: org.hibernate.dialect.PostgreSQL9Dialect
  mail:
    host: mail.nzesportes.com.br
    port: 587
    username: 'nzesportes@nzesportes.com.br'
    password: '7q=4rG{8y-Cl'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: false
      test-connection: true
flyway:
  locations: filesystem:db/migration
  password: postgres
  url: jdbc:postgresql://localhost:5432/postgres
  user: postgres
nz:
  mercado-pago:
    token: 'TEST-8650980122344492-060206-2034e445ddd4e824b8189a3dc1fd50dd-292462796'
    url: 'https://api.mercadopago.com/'
    auto-return: approved
    payment:
      back-url: 'http://localhost:4200/minha-conta/meus-pedidos'
  melhor-envio:
    url: 'https://sandbox.melhorenvio.com.br/'
    client-id: '2555'
    client-secret: 'tiiR7309zmoB1S21IpqGEETtvWq0Q9XhcVPlYx44'
    user-agent: 'nzesportes-dev (andrelive.05@hotmail.com)'
    redirect-uri: 'https://nzesportes-dev-front.herokuapp.com/painel/melhor-envio/codigo'
  webhook: 'https://webhook.site/f222a156-97c5-4c34-a970-5d8786b96398'
  first-access:
    url: 'http://localhost:4200/auth/first-access/'
  recovery:
    url: 'http://localhost:4200/auth/recovery/'
  email:
    from: 'nzesportes@nzesportes.com.br'
  front:
    url: 'http://localhost:4200/'
  allowed:
    origin: '*'
  jwt:
    secret: secretofdonossousjwt
    expiration: 86400000