server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    hikari:
      maximumPoolSize: 20
      max-active: 20
      max-idle: 10
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345
  jpa:
    databasePlatform: org.hibernate.dialect.PostgreSQL9Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${NZ_EMAIL:''}
    password: ${NZ_PASSWORD:''}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: false
      test-connection: true
flyway:
  locations: filesystem:db/migration
  password: postgres
  url: jdbc:postgresql://localhost:5432/postgres
  user: postgres
nz:
  melhor-envio:
    url: $MELHOR_ENVIO_URL
    client-id: $CLIENT_ID
    client-secret: $CLIENT_SECRET
    user-agent: $USER_AGENT
    redirect-uri: $REDIRECT_URI
  first-access:
    url: 'http://localhost:4200/auth/first-access/'
  recovery:
    url: 'http://localhost:4200/auth/recovery/'
  email:
    from: 'nao-responda@nzesportes'
  allowed:
    origin: '*'
  jwt:
    secret: secretofdonossousjwt
    expiration: 86400000
