server:
  port: 8080
spring:
  datasource:
    hikari:
      maximumPoolSize: 20
      max-active: 20
      max-idle: 10
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: 12345
  jpa:
    databasePlatform: org.hibernate.dialect.PostgreSQL9Dialect
flyway:
  locations: filesystem:db/migration
  password: 12345
  url: jdbc:postgresql://localhost:5432/
  user: postgres
nz:
  allowed:
    origin: '*'
  jwt:
    secret: secretofdonossousjwt
    expiration: 86400000