on:
  push:
    branches:
      - main
name: 🚀 Deploy prod website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Restart application deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEPLOY }}
          username: ${{ secrets.SSH_USERNAME_DEPLOY }}
          password: ${{ secrets.SSH_PASSWORD_DEPLOY }}
          port: ${{ secrets.SSH_PORT_DEPLOY }}
          script: ${{ secrets.SSH_SCRIPT_DEPLOY_BACK }}